### ISSUE TITLE
International Date format yyyy-MM-dd error

### ISSUE THREAD

**Issue by frablaser** [ryanelian/FluentValidation.Blazor#34]
Hi Ryan,

I talked to Jeremy Skinner about that problem:
https://github.com/FluentValidation/FluentValidation/issues/1490

Because that error become just after the validation has been executed, I wonder know if it could be caused by the FluentValidator...?

Regards...

**Comment by ryanelian** [comment]
I need a description of your problem AND codes, I cannot just magically fix your issue. Please provide repros.

**Comment by frablaser** [comment]
It was already there... 😉
![image](https://user-images.githubusercontent.com/29067539/90625102-10933800-e1e7-11ea-822e-5c321894565b.png)

Here is the link
[https://github.com/frablaser/ErrorDateFireFox](https://github.com/frablaser/ErrorDateFireFox)

**Comment by ryanelian** [comment]
This is not caused by `FluentValidation` nor `FluentValidation.Blazor`

This is because you've written a not-valid `ValidationMessage` component:

```html
<ValidationMessage For="() => person.PersonBirthDate" @Required="true" />
```

`@Required="true"` is not a valid attribute of `ValidationMessage`.

Please read the documentation for `ValidationMessage` component in the Blazor official documentation carefully: https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1#validation-summary-and-validation-message-components

**Comment by frablaser** [comment]
> 
> 
> This is not caused by `FluentValidation` nor `FluentValidation.Blazor`
> 
> This is because you've written a not-valid `ValidationMessage` component:
> 
> ```
> <ValidationMessage For="() => person.PersonBirthDate" @Required="true" />
> ```
> 
> `@Required="true"` is not a valid attribute of `ValidationMessage`.
> 

You're right! I forgot this one... Since I removed it, it worked perfectly... 
Thanks! ;)
