### ISSUE TITLE
Problem having complex MUST()

### ISSUE THREAD

**Issue by baer999** [ryanelian/FluentValidation.Blazor#7]
Hello,
I want to have a complex Rule that checks if a given Date is in a List of objects that are stored in a Service registered class.
Problem now is that I'm not able to use the parent object in the Must() method and also I'm not able to get the values out of the registered Service, right?

Here you can see my try of creating a Rule:

https://ibb.co/M2mVkBw

In my parent object (AbstractValidator<Form_Checkout>) I have also a property with the required values, but can't access it in Must method.

Any hint how I can solve my issue?

Thx!

**Comment by ryanelian** [comment]
I'm sorry for the very late response. Many things are going on IRL.

> Problem now is that I'm not able to use the parent object in the Must() method and also I'm not able to get the values out of the registered Service, right?

Yes.

This limitation is due to how validations are processed in Blazor. That said, you can access the parent object by somehow attaching it to the child object as reference. Crazy I know, but should solve your problem nonetheless:

```cs
public class Parent
{
    public List<Child> Children { set; get; }
}

public class Child
{
    public Parent Parent { set; get; }
}
```
